name: cd-ts
channels:
  - defaults
  - conda-forge
dependencies:
  - r-base
  - r-dplyr
  - r-BigVAR
  - r-data.table
  - r-reticulate
  - python=3.9.0
  - pandas
  - numpy
  - scipy
  - pdblp
  - tqdm
  - jupyterlab
  - pytorch
  - pyg-lib
  - networkx
  - scikit-learn
