name: cd-ts
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - r-base
  - r-dplyr
  - r-BigVAR
  - r-data.table
  - r-reticulate
  - mkl < 2022
  - python=3.10.0
  - pandas
  - numpy
  - scipy
  - pdblp
  - tqdm
  - jupyterlab
  - pyg-lib
  - pygod
  - pytorch
  - torchvision 
  - torchaudio 
  - pyg 
  - pytorch-sparse 
  - networkx
  - scikit-learn
