name: cd-ts
channels:
  - defaults
  - conda-forge
dependencies:
  - r-base
  - r-dplyr
  - r-BigVAR
  - r-data.table
  - r-reticulate
  - python
  - pandas
  - numpy
  - pdblp
  - tqdm
  - jupyterlab
